# Generated by Django 2.2.6 on 2019-10-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='shirt_size',
            new_name='permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
