# Generated by Django 2.2.6 on 2019-10-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0002_auto_20191027_1025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
